// Cotos y parques micológicos regulados (permiso de pago).
// Coordenadas en el MONTE (no en el pueblo): punto con arbolado verificado
// uno a uno con MFE ff_uso (oct-2026). Siguen siendo ORIENTATIVAS:
// el coto abarca varios montes; verifica norma y permiso vigentes.
// Fuentes: micocyl.es / micologiacyl.es (CyL), micoaragon.es (Aragón),
// Gobierno de Navarra (Ultzama, Erro, Aezkoa, Roncal, Salazar),
// Ayuntamiento Soto del Real MUP-141 (Madrid), PN Poblet (Cataluña).
// En Cataluña casi todo el monte es libre (3 kg): aquí solo el piloto de Poblet.
const COTOS=[
{u:"https://permisos.micologiacyl.es/acotados",n:"Pinares de Urbión (Soria)",la:41.93,lo:-2.86,ccaa:"Castilla y León"},
{u:"https://permisos.micologiacyl.es/acotados",n:"Montes de Soria",la:41.8093,lo:-2.543,ccaa:"Castilla y León"},
{u:"https://permisos.micologiacyl.es/acotados",n:"Montes CyL Soria (SO-50003)",la:41.9478,lo:-2.4773,ccaa:"Castilla y León"},
{u:"https://permisos.micologiacyl.es/acotados",n:"Demanda-San Millán (Burgos)",la:42.2195,lo:-3.3109,ccaa:"Castilla y León"},
{u:"https://permisos.micologiacyl.es/acotados",n:"Montes de Oca (Burgos)",la:42.3587,lo:-3.3512,ccaa:"Castilla y León"},
{u:"https://permisos.micologiacyl.es/acotados",n:"Fresneda Sierra Tirón (Burgos)",la:42.2778,lo:-3.1302,ccaa:"Castilla y León"},
{u:"https://permisos.micologiacyl.es/acotados",n:"Valle de Mena (Burgos)",la:43.0957,lo:-3.272,ccaa:"Castilla y León"},
{u:"https://permisos.micologiacyl.es/acotados",n:"San Zadornil (Burgos)",la:42.8364,lo:-3.1731,ccaa:"Castilla y León"},
{u:"https://permisos.micologiacyl.es/acotados",n:"Gredos (Ávila)",la:40.4042,lo:-4.8,ccaa:"Castilla y León"},
{u:"https://permisos.micologiacyl.es/acotados",n:"Montes CyL Ávila (AV-50006)",la:40.2758,lo:-5.1234,ccaa:"Castilla y León"},
{u:"https://www.peguerinos.es/ocio-y-turismo/micologia/aprovechamiento-micologico-municipal.html",n:"Peguerinos (Ávila, AV-50009)",la:40.6392,lo:-4.2192,ccaa:"Castilla y León"},
{u:"https://permisos.micologiacyl.es/acotados",n:"Montes de Segovia (SG-50002)",la:41.1172,lo:-3.7727,ccaa:"Castilla y León"},
{u:"https://permisos.micologiacyl.es/acotados",n:"Montes CyL Segovia (SG-50005)",la:41.0608,lo:-3.8141,ccaa:"Castilla y León"},
{u:"https://permisos.micologiacyl.es/acotados",n:"Río Cea (León)",la:42.7693,lo:-5.0176,ccaa:"Castilla y León"},
{u:"https://permisos.micologiacyl.es/acotados",n:"Torozos-Mayorga-Valladolid",la:41.5283,lo:-4.688,ccaa:"Castilla y León"},
{u:"https://permisos.micologiacyl.es/acotados",n:"Noroeste Zamorano (Zamora)",la:41.9217,lo:-6.3335,ccaa:"Castilla y León"},
{u:"https://permisos.micologiacyl.es/acotados",n:"Camarzana-Rabanales (Zamora)",la:41.7952,lo:-6.2174,ccaa:"Castilla y León"},
{u:"https://permisos.micologiacyl.es/acotados",n:"Velilla del Río Carrión (Palencia)",la:42.8896,lo:-4.7869,ccaa:"Castilla y León"},
{u:"https://permisos.micologiacyl.es/acotados",n:"Triollo (Palencia)",la:42.9465,lo:-4.6644,ccaa:"Castilla y León"},
{u:"https://permisos.micologiacyl.es/acotados",n:"Sierras Francia-Béjar (Salamanca)",la:40.4282,lo:-6.2924,ccaa:"Castilla y León"},
{u:"https://permisos.micologiacyl.es/acotados",n:"Ribera de Cañedo (Salamanca)",la:41.2142,lo:-5.8162,ccaa:"Castilla y León"},
{u:"https://permisos.micologiacyl.es/acotados",n:"Aguilar de Campoo (Palencia)",la:42.7867,lo:-4.2702,ccaa:"Castilla y León"},
{u:"https://permisos.micologiacyl.es/acotados",n:"Barbadillo del Mercado (Burgos)",la:41.9639,lo:-3.3547,ccaa:"Castilla y León"},
{u:"https://www.micoaragon.es",n:"Comunidad de Albarracín (Teruel)",la:40.5049,lo:-1.5886,ccaa:"Aragón"},
{u:"https://www.micoaragon.es",n:"Moncayo (Zaragoza)",la:41.7746,lo:-1.7211,ccaa:"Aragón"},
{u:"https://www.micoaragon.es",n:"Maestrazgo (Teruel)",la:40.5051,lo:-0.5288,ccaa:"Aragón"},
{u:"https://parquemicologicoultzama.com/es/permisos/2",n:"Ultzama (Navarra)",la:42.9632,lo:-1.6828,ccaa:"Navarra"},
{u:"https://www.parquemicologicoerro.com/permisos",n:"Erro-Roncesvalles (Navarra)",la:43.0132,lo:-1.3202,ccaa:"Navarra"},
{u:"https://www.irati.org/micologia",n:"Aezkoa-Irati (Navarra)",la:42.9046,lo:-1.0926,ccaa:"Navarra"},
{u:"https://www.navarra.es/es/medio-ambiente/setas-y-hongos",n:"Roncal (Navarra)",la:42.8729,lo:-0.9111,ccaa:"Navarra"},
{u:"https://www.irati.org/micologia",n:"Salazar (Navarra)",la:42.8507,lo:-1.0991,ccaa:"Navarra"},
{u:"https://permisos.setaspedrizasanblas.es/licencia",n:"Soto del Real MUP-141 (Madrid)",la:40.7358,lo:-3.9416,ccaa:"Comunidad de Madrid"},
{n:"Poblet (Tarragona, piloto)",la:41.3282,lo:1.0461,ccaa:"Cataluña"},
{u:"https://www.gorbeiamikologia.eus/es/permisos/",n:"Gorbeialdea (Álava)",la:42.9563,lo:-2.8117,ccaa:"País Vasco"},
{u:"https://www.asparrena.eus/ocio-y-turismo/parque-micologico-asparrena-san-millan",n:"Asparrena (Álava)",la:42.9016,lo:-2.3176,ccaa:"País Vasco"},
{u:"https://www.arraia-maeztu.eus/servicios/coto-de-setas/",n:"Arraia-Maeztu (Álava)",la:42.7465,lo:-2.4473,ccaa:"País Vasco"},
{u:"https://web.araba.eus/es/montes/aprovechamiento-de-hongos-flores-y-frutos-silvestres",n:"Valdegovía-Árcena (Álava)",la:42.8556,lo:-3.061,ccaa:"País Vasco"},
{u:"https://web.araba.eus/es/montes/aprovechamiento-de-hongos-flores-y-frutos-silvestres",n:"Gordoa-Oraneta (Álava)",la:42.9197,lo:-2.3717,ccaa:"País Vasco"},
{u:"https://micocebollera.com/",n:"Sierra de Cebollera (La Rioja)",la:42.1178,lo:-2.6733,ccaa:"La Rioja"},
{u:"http://micocameros.com/",n:"El Rasillo (La Rioja)",la:42.1989,lo:-2.6974,ccaa:"La Rioja"},
{u:"https://micomoncalvillo.com/",n:"Moncalvillo (La Rioja)",la:42.3122,lo:-2.5338,ccaa:"La Rioja"},
{u:"https://micoviniegradearriba.com/",n:"Viniegra de Arriba (La Rioja)",la:42.0953,lo:-2.8255,ccaa:"La Rioja"},
{u:"http://ortigosa.gestionreservas.es/",n:"Ortigosa (La Rioja)",la:42.1591,lo:-2.7154,ccaa:"La Rioja"},
{u:"https://nievadecameros.com/area-recoleccion",n:"Nieva de Cameros (La Rioja)",la:42.2287,lo:-2.6856,ccaa:"La Rioja"},
{u:"https://www.larioja.org/medio-ambiente/es/gestion-forestal/aprovechamiento-setas",n:"Santurdejo (La Rioja)",la:42.3685,lo:-2.9413,ccaa:"La Rioja"},
{u:"https://www.larioja.org/medio-ambiente/es/gestion-forestal/aprovechamiento-setas",n:"Santa Coloma (La Rioja)",la:42.3642,lo:-2.6564,ccaa:"La Rioja"},
{u:"https://www.larioja.org/medio-ambiente/es/gestion-forestal/aprovechamiento-setas",n:"Ventosa (La Rioja)",la:42.4042,lo:-2.6263,ccaa:"La Rioja"},
{u:"https://www.larioja.org/medio-ambiente/es/gestion-forestal/aprovechamiento-setas",n:"Sotés (La Rioja)",la:42.4003,lo:-2.6019,ccaa:"La Rioja"},
{u:"https://www.larioja.org/medio-ambiente/es/gestion-forestal/aprovechamiento-setas",n:"Nestares (La Rioja)",la:42.2664,lo:-2.6199,ccaa:"La Rioja"},
{u:"https://www.larioja.org/medio-ambiente/es/gestion-forestal/aprovechamiento-setas",n:"Cornago (La Rioja)",la:42.0658,lo:-2.094,ccaa:"La Rioja"},
{u:"https://www.larioja.org/medio-ambiente/es/gestion-forestal/aprovechamiento-setas",n:"Igea (La Rioja)",la:42.0686,lo:-2.0093,ccaa:"La Rioja"},
{u:"https://www.boal.es/en/recogida-de-setas",n:"Boal (Asturias)",la:43.4102,lo:-6.8352,ccaa:"Asturias"},
{u:"https://www.miera.es",n:"Miera (Cantabria)",la:43.2754,lo:-3.7086,ccaa:"Cantabria"},
{u:"https://sierraaltotajo.es/micoturismo/condiciones-permisos",n:"Alto Tajo (Guadalajara)",la:40.5568,lo:-1.7193,ccaa:"Castilla-La Mancha"},
{u:"https://www.serradilla.es",n:"Dehesa Boyal-Serradilla (Cáceres)",la:39.8415,lo:-6.1399,ccaa:"Extremadura"},
{u:"https://www.mirafloresdelasierra.es/sin-categoria/precios-informacion-especies-micologicas/",n:"Miraflores de la Sierra (Madrid)",la:40.8098,lo:-3.7667,ccaa:"Comunidad de Madrid"},
{u:"https://www.rascafria.org/informacion-micologica/",n:"Rascafría (Madrid)",la:40.8999,lo:-3.8803,ccaa:"Comunidad de Madrid"},
{u:"https://www.lozoya.es/coto-micologico/",n:"Lozoya (Madrid)",la:40.9672,lo:-3.784,ccaa:"Comunidad de Madrid"},
{u:"https://www.canencia.es/tu-ayuntamiento/normativa-municipal/ordenanzas-municipales/689-ordenanza-municipal-reguladora-del-aprovechamiento-micologico-en-el-termino-municipal-de-canencia-madrid",n:"Canencia (Madrid)",la:40.9136,lo:-3.7376,ccaa:"Comunidad de Madrid"},
{u:"https://www.bocm.es/boletin/CM_Orden_BOCM/2025/07/18/BOCM-20250718-52.PDF",n:"Bustarviejo (Madrid)",la:40.8508,lo:-3.7098,ccaa:"Comunidad de Madrid"},
{u:"https://www.bayarcal.es/",n:"Bayárcal (Almería)",la:37.03,lo:-2.9992,ccaa:"Andalucía"},
{u:"https://ayuntamientodebaza.es/economia-y-empresa/normativa-municipal/ordenanzas-fiscales/",n:"Sierra de Baza (Granada)",la:37.4282,lo:-2.8475,ccaa:"Andalucía"},
{u:"https://sede.tenerife.es/es/tramites-y-servicios/item/2866-comunicacion-mediante-declaracion-responsable-para-la-recogida-de-setas-en-el-paisaje-protegido-de-las-lagunetas-y-en-el-parque-natural-de-corona-forestal",n:"Corona Forestal-Lagunetas (Tenerife)",la:28.4604,lo:-16.367,ccaa:"Canarias"},
{u:"https://cabildo.grancanaria.com/osorio/visita-a-la-finca-y-otras-actividades",n:"Osorio-Teror (Gran Canaria)",la:28.0598,lo:-15.5534,ccaa:"Canarias"}
];
